### PR TITLE
Move redirect inside success handler

### PR DESCRIPTION
**Pull request by dustinnewman98**
## Description
Clears up the code structure a little by moving the redirect to only fire upon success.

### CODE REVIEW

**Comment by dustinnewman98** [comment]
@alexanderqchen Addressed concerns!

**Comment by alexanderqchen** [comment]
Ok great! Should I deploy this rn?

**Comment by dustinnewman98** [comment]
@alexanderqchen I believe so, yeah! If it looks good to you!

**Comment by alexanderqchen** [comment]
Ok, will do!

**Pull request merged**
